In [1]:
import pandas as pd

In [2]:
regions = [
    '강원',
    '경기',
    '경남',
    '경북',
    '광주',
    '대구',
    '대전',
    '부산',
    '서울',
    '세종',
    '울산',
    '인천',
    '전남',
    '전북',
    '제주',
    '충남',
    '충북'
]

In [3]:
col = pd.read_csv(f'./data/소상공인시장진흥공단_상가(상권)정보_강원_202206.csv').columns
col

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [4]:
pd.DataFrame(index=col)

Empty DataFrame
Columns: []
Index: [상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분류코드, 상권업종중분류명, 상권업종소분류코드, 상권업종소분류명, 표준산업분류코드, 표준산업분류명, 시도코드, 시도명, 시군구코드, 시군구명, 행정동코드, 행정동명, 법정동코드, 법정동명, 지번코드, 대지구분코드, 대지구분명, 지번본번지, 지번부번지, 지번주소, 도로명코드, 도로명, 건물본번지, 건물부번지, 건물관리번호, 건물명, 도로명주소, 구우편번호, 신우편번호, 동정보, 층정보, 호정보, 경도, 위도]

In [5]:
data = pd.DataFrame()
for region in regions:
    temp = pd.read_csv(f'./data/소상공인시장진흥공단_상가(상권)정보_{region}_202206.csv')
    temp.insert(0,'지역',region)
    data = data.append(temp)
data

C:\Users\gw\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3251: DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,지역,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,강원,25033300,동그라미중고타이어,NaN,D,소매,D23,자동차/자동차용품,D23A04,타이어판매,...,4215011100110960006010791,NaN,강원도 강릉시 가작로 270,210110.0,25488.0,1,NaN,NaN,128.904472,37.770252
1,강원,17174549,세인트존스호텔Ohcrab,NaN,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,...,4215011300100010001017124,세인트존스호텔,강원도 강릉시 창해로 307,210120.0,25467.0,NaN,NaN,NaN,128.920908,37.791299
2,강원,17174079,평창라마다호텔,NaN,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,...,4276038024102450036000001,NaN,강원도 평창군 대관령면 오목길 107,232954.0,25342.0,NaN,NaN,NaN,128.717971,37.660051
3,강원,17173904,호텔탑스텐스카이라운지,NaN,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,...,4215035029100920001000002,NaN,강원도 강릉시 옥계면 헌화로 455-34,210831.0,25633.0,NaN,NaN,NaN,129.052902,37.654680
4,강원,24412526,레이디가구,NaN,D,소매,D15,가구소매,D15A01,일반가구소매,...,4213011500111400020035715,NaN,강원도 원주시 송삼길 156-19,220150.0,26385.0,NaN,NaN,NaN,127.917307,37.327668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91851,충북,18464876,광수가코다리,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,...,4371025346004280007001720,NaN,충청북도 청주시 청원구 오창읍 과학산업2로 271,363884.0,28121.0,NaN,1,NaN,127.414962,36.709197
91852,충북,18469519,파티라운지운천,NaN,D,소매,D02,선물/팬시/기념품,D02A02,꽃집/꽃배달,...,4311310400109520000015777,NaN,충청북도 청주시 흥덕구 사운로187번길 64-2,361841.0,28471.0,NaN,NaN,NaN,127.474862,36.644013
91853,충북,18444490,도배,NaN,F,생활서비스,F15,주택수리,F15A02,미장타일도배도장,...,4311310200102310017003360,세종회관,충청북도 청주시 서원구 사직대로 133-1,362832.0,28567.0,NaN,NaN,NaN,127.462285,36.635306
91854,충북,18446727,황금물류,NaN,F,생활서비스,F08,대행업,F08A03,고객관리대행,...,4311112000101990001048789,금천현대아파트,충청북도 청주시 상당구 중고개로337번길 23,360766.0,28727.0,113,NaN,NaN,127.504480,36.629324
91855,충북,18446594,호수농원,NaN,F,생활서비스,F08,대행업,F08A07,이민유학알선,...,4373038028104870001000001,NaN,충청북도 옥천군 군북면 추소길 40-1,373853.0,29004.0,NaN,NaN,NaN,127.563261,36.348981

In [6]:
data.to_csv('data.csv',index=False)
data.head()

,지역,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,강원,25033300,동그라미중고타이어,NaN,D,소매,D23,자동차/자동차용품,D23A04,타이어판매,...,4215011100110960006010791,NaN,강원도 강릉시 가작로 270,210110.0,25488.0,1,NaN,NaN,128.904472,37.770252
1,강원,17174549,세인트존스호텔Ohcrab,NaN,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,...,4215011300100010001017124,세인트존스호텔,강원도 강릉시 창해로 307,210120.0,25467.0,NaN,NaN,NaN,128.920908,37.791299
2,강원,17174079,평창라마다호텔,NaN,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,...,4276038024102450036000001,NaN,강원도 평창군 대관령면 오목길 107,232954.0,25342.0,NaN,NaN,NaN,128.717971,37.660051
3,강원,17173904,호텔탑스텐스카이라운지,NaN,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,...,4215035029100920001000002,NaN,강원도 강릉시 옥계면 헌화로 455-34,210831.0,25633.0,NaN,NaN,NaN,129.052902,37.654680
4,강원,24412526,레이디가구,NaN,D,소매,D15,가구소매,D15A01,일반가구소매,...,4213011500111400020035715,NaN,강원도 원주시 송삼길 156-19,220150.0,26385.0,NaN,NaN,NaN,127.917307,37.327668